# Generated by Django 5.0.2 on 2024-03-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitors',
            name='mobile_number',
            field=models.CharField(max_length=100),
        ),
    ]
