# Generated by Django 5.0.2 on 2024-03-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitorsapp', '0002_alter_visitors_mobile_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Visitors',
            new_name='Visitor',
        ),
    ]
